---
title:
    "Welcome to the Shiny version of baymedr"
author:
    "Maximilian Linde"
date:
    "`r format(Sys.time(), '%d %B, %Y')`"
output:
    md_document:
bibliography:
    references.bib
csl:
    apa7.csl
---

# Bayes Factors for Superiority, Non-inferiority, and Equivalence Designs

Welcome. This website allows you to easily calculate Bayes factors for the superiority, non-inferiority, and equivalence designs. This website was built using Shiny and implements the baymedr software [@LindeVanravenzwaaij2019_0.1.0], written in R [@Rcoreteam2019], that was specifically developed to calculate Bayes factors for these three designs. Usage of this Shiny app does not require any programming skills and is, thus, immediately accessible for every researcher.

## Bayes factors

bla bla bla

## Superiority

The superiority test gathers evidence of whether the experimental group is superior to the control group. Importantly, sometimes low and sometimes high values on the measure of interest represent superiority. By its very nature, the superiority test consists of a one-sided test. Oftentimes, however, the superiority test is conducted as a two-sided test with subsequent confirmation that the effect goes in the expected direction.

## Non-inferiority

The non-inferiority test gathers evidence of whether the experimental condition is not worse by a certain amount - which is given by the non-inferiority margin - than the control group. Here as well, sometimes low and sometimes high values on the outcome measure represent non-inferiority.

## Equivalence

The equivalence test gathers evidence of whether the experimental and control groups are (practically) equivalent on some outcome measure. Equivalence could be defined by an interval that contains all the values that are considered practically equivalent to no effect or by setting a point null hypothesis.

## References